### ISSUE TITLE
Observers not called when the activity is in background

### ISSUE THREAD

**Issue by marcauberer** [ibrahimsn98/live-preferences#4]
Before you say it: I know this is a possible dupe of #1, but I'm not able to reopen it.

Following situation:
I have a fragment, which listenes to a boolean preference, which can only be changed by another activity. Whenever the first activity gets paused, the observers are not active any more. When then the first activity gets resumed, the observer gets called in every case. Even if the preference did not change.
This might be a possible bug.

**Comment by marcauberer** [comment]
Can this be confirmed?

**Comment by ibrahimsn98** [comment]
Hello @marcauberer you may check the Release 1.9. Please let me know if the problem still occurs.

**Comment by marcauberer** [comment]
Okay. The observers are now called correctly. They won't be called until the first activity resumes, but that is okay, cause it only has to redraw while its on-screen.
Thanks for solving this. Awesome lib!

**Comment by jdubb6644** [comment]
Sweet man glad you figured it out
